<a href="https://colab.research.google.com/github/NafisFuadTanvir/Machine-learning-works/blob/main/practise_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(arr.shape)

[1 2 3]
(3,)


In [ ]:
matrix=np.array([[1,2,3],[10,12,13]])
print(matrix)
print(matrix.shape)

[[ 1  2  3]
 [10 12 13]]
(2, 3)


In [ ]:
#indexing and slicing
a = np.array([10, 20, 30, 40])
print(a[0])
print(a[-1])


10
40


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[1, 2])
print(b[:, 1])

6
[2 5]


In [ ]:
#maths

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x * y)
print(np.dot(x, y))
print(np.sum(x))
print(np.mean(x))
print(np.std(x))


[5 7 9]
[ 4 10 18]
32
6
2.0
0.816496580927726


In [ ]:
#axis wise operations

a = np.array([[1, 2], [3, 4]])

print(np.sum(a, axis=0))  # sum of columns → [4 6]
print(np.sum(a, axis=1))  # sum of rows → [3 7]


[4 6]
[3 7]


In [ ]:
#Random Numbers
np.random.seed(42)                  # for reproducibility
np.random.rand(3)                   # [0.37454012 0.95071431 0.73199394]
np.random.randn(2, 3)               # standard normal distribution
np.random.randint(1, 10, size=5)    # 5 random integers from 1 to 9


array([5, 1, 6, 9, 1])

In [ ]:
a = np.array([1, 2, 3])
print(np.argmax(a))     # index of max element → 2
print(np.argmin(a))     # index of min element → 0
print(np.unique([1,2,2,3,3,3]))  # [1 2 3]


2
0
[1 2 3]


In [ ]:
#Practical Example: Standardization (Important for ML)
data = np.array([10, 20, 30, 40, 50])
mean = np.mean(data)
std = np.std(data)

standardized = (data - mean) / std
print(standardized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
